name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Build app
        run: echo "Building app..."

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: production   # 👈 This triggers the approval gate
    steps:
      - name: Deploy
        run: echo "Deploying to production..."
